# Generated by Django 6.0 on 2025-12-29 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('total_rooms', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('joined_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='Rentapp.house')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='Rentapp.house')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=30)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Rentapp.house')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rentapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rents', to='Rentapp.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rents', to='Rentapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Delivered', 'delivered'), ('Failed', 'failed')], default='Delivered', max_length=20)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rentapp.smstemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('online', 'Online'), ('cash', 'Cash')], max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentapp.monthlyrent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Rentapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantRecordManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rental_agreement', models.FileField(blank=True, null=True, upload_to='documents/rentals/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='documents/id_proof/')),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rentapp.room')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_record', to='Rentapp.tenant')),
            ],
        ),
    ]
